name: buienradar
on:
  schedule:
    - cron: "15/30 4-21 * * *"
  workflow_dispatch:
jobs:
  tests:
    uses: ./.github/workflows/_reusable.yml
    with:
      playwright-test-cmd: npx playwright test tests/buienradar.spec.ts --project=firefox
      diff-cmd: $(git diff HEAD^ HEAD --name-only --diff-filter=A ':scrapes/buienradar/*')