name: flights
on:
  schedule:
    - cron: "37 4-22/4 * * *"
  workflow_dispatch:
jobs:
  tests:
    uses: ./.github/workflows/_reusable.yml
    with:
      playwright-test-cmd: npx playwright test tests/flights.spec.ts --project=firefox
      diff-cmd: $(git diff HEAD^ HEAD --name-only --diff-filter=M ':scrapes/flights/*.md' | sed -r 's/(\w+)\/(.*)\.md$/\2/' | xargs | sed -e 's/ /, /g')
      notfication-img: scrapes/flights/prices.png
    secrets:
      telegram-to: ${{ secrets.TELEGRAM_TO }}
      telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
