name: Playwright Tests
on:
  schedule:
    - cron: "5/30 4-21 * * *"
  workflow_dispatch:
jobs:
  tests:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    outputs:
      web-aler-ts-vgcchanges: ${{steps.try-commit-push.outputs.web-aler-ts-vgcchanges}}
      web-aler-ts-brchanges: ${{steps.try-commit-push.outputs.web-aler-ts-brchanges}}
      web-aler-ts-url: ${{steps.try-commit-push.outputs.web-aler-ts-url}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps firefox
    - name: Run Playwright tests
      run: npx playwright test --project=firefox
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15
    - name: Commit and push if changes occured
      id: try-commit-push
      if: success()
      # changing from set-output to GITHUB_OUTPUT https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
      run: |-
        git config --global user.name 'gvdenbro from gh action'
        git config --global user.email 'gvdenbro@users.noreply.github.com'
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest scraping data: ${timestamp}" || exit 0
        vgcchanges="$(git diff HEAD^ HEAD --name-only --diff-filter=AM --exit-code ':scrapes/vgc*.md' | sed -r 's/(\w+)\/(.*)\.md$/\2/' | xargs | sed -e 's/ /, /g')"
        brchanges="$(git diff HEAD^ HEAD --name-only --diff-filter=A ':scrapes/buienradar/*')"
        git push
        echo "web-aler-ts-vgcchanges=$vgcchanges" >> $GITHUB_OUTPUT
        echo "web-aler-ts-brchanges=$brchanges" >> $GITHUB_OUTPUT
        echo "web-aler-ts-url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
  notify-vgc:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Notify vgc telegram
      uses: appleboy/telegram-action@master
      if: ${{ success() && needs.tests.outputs.web-aler-ts-vgcchanges != ''}}
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "[vgc web alerts - view changes](${{needs.tests.outputs.web-aler-ts-url}}):\n${{needs.tests.outputs.web-aler-ts-vgcchanges}}"
        format: markdown
  notify-buienradar:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Notify buienradar telegram
      uses: appleboy/telegram-action@master
      if: ${{ success() && needs.tests.outputs.web-aler-ts-brchanges != ''}}
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "[buienradar web alerts - view changes](${{needs.tests.outputs.web-aler-ts-url}})"
        photo: scrapes/buienradar/screenshot.png
        format: markdown