name: taiwan
on:
  # schedule:
  #   - cron: "30 4-22/6 * * *"
  workflow_dispatch:
jobs:
  tests:
    uses: ./.github/workflows/_reusable.yml
    with:
      playwright-test-cmd: npx playwright test tests/taiwan.spec.ts --project=firefox
      diff-cmd: $(git diff HEAD^ HEAD --name-only --diff-filter=M ':scrapes/taiwan/*.md' | sed -r 's/(\w+)\/(.*)\.md$/\2/' | xargs | sed -e 's/ /, /g')
    secrets:
      telegram-to: ${{ secrets.TELEGRAM_TO }}
      telegram-token: ${{ secrets.TELEGRAM_TOKEN }}